# Generated by Django 5.2.8 on 2025-11-18 15:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_laundryshop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.AddField(
            model_name='order',
            name='cloth_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Washing', 'Washing'), ('Drying', 'Drying'), ('Ironing', 'Ironing'), ('Ready', 'Ready for Pickup'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.laundryshop'),
        ),
    ]
