# Generated by Django 5.2.8 on 2025-11-20 05:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_remove_order_status_order_cloth_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='laundryshop',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laundryshop',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laundryshop',
            name='password',
            field=models.CharField(default='temporarypassword', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='laundryshop',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
