# Generated by Django 5.2.4 on 2025-11-21 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_service_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='services',
        ),
        migrations.AddField(
            model_name='service',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='shop.branch'),
        ),
        migrations.AlterUniqueTogether(
            name='service',
            unique_together={('branch', 'name')},
        ),
        migrations.RemoveField(
            model_name='service',
            name='shop',
        ),
    ]
