# Generated by Django 5.2.8 on 2025-11-21 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_remove_branch_services_alter_service_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='shop.branch'),
            preserve_default=False,
        ),
    ]
