# Generated by Django 5.2.4 on 2025-11-21 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_service_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='laundryshop',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
