# Generated by Django 5.2.4 on 2025-11-21 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_profile_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='laundryshop',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
