# Generated by Django 5.2.4 on 2025-11-21 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_laundryshop_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='laundryshop',
            name='latitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='laundryshop',
            name='longitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
