# Generated by Django 5.2.4 on 2025-11-21 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_laundryshop_latitude_laundryshop_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('hi', 'हिंदी (Hindi)'), ('mr', 'मराठी (Marathi)'), ('gu', 'ગુજરાતી (Gujarati)'), ('ta', 'தமிழ் (Tamil)'), ('te', 'తెలుగు (Telugu)'), ('kn', 'ಕನ್ನಡ (Kannada)'), ('ml', 'മലയാളം (Malayalam)'), ('bn', 'বাংলা (Bengali)'), ('pa', 'ਪੰਜਾਬੀ (Punjabi)')], default='en', max_length=2),
        ),
    ]
