# Generated by Django 5.2.4 on 2025-11-21 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_profile_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='language',
        ),
    ]
