# Generated by Django 5.2.4 on 2025-11-25 05:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_order_branch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('order_placed', 'Order Placed'), ('status_update', 'Status Update'), ('ready_pickup', 'Ready for Pickup'), ('completed', 'Order Completed'), ('welcome', 'Welcome'), ('profile_reminder', 'Profile Reminder'), ('explore_services', 'Explore Services')], max_length=20)),
                ('icon', models.CharField(default='fas fa-bell', max_length=50)),
                ('color', models.CharField(default='#3498db', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
