# Generated by Django 5.2.4 on 2025-11-25 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='notifications_enabled',
            field=models.BooleanField(default=True, help_text='Enable notification badges and alerts'),
        ),
    ]
