# Generated by Django 5.2.4 on 2025-11-28 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_profile_notifications_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_verified',
            field=models.BooleanField(default=False, help_text="Whether the user's email has been verified"),
        ),
    ]
